apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostservice
spec:
  selector:
    matchLabels:
      app: hostservice
  template:
    metadata:
      labels:
        app: hostservice
    spec:
      containers:
      - name: hostservice-container
        image: ankisile/hostservice:08ddf14c6f5bbfcec16845273c8ed41a8fb444f5
        ports:
        - containerPort: 8080
