apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostservice
spec:
  selector:
    matchLabels:
      app: hostservice
  template:
    metadata:
      labels:
        app: hostservice
    spec:
      containers:
      - name: hostservice-container
        image: ankisile/nodeapp:75f50511e55e9e381cdedec22b0d2682166bcdb0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
