apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostservice
spec:
  selector:
    matchLabels:
      app: hostservice
  template:
    metadata:
      labels:
        app: hostservice
    spec:
      containers:
      - name: hostservice-container
        image: ankisile/hostservice:6d6cd14075b1f0f6faf825664106ba9889f02341
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
