apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostservice
spec:
  selector:
    matchLabels:
      app: hostservice
  template:
    metadata:
      labels:
        app: hostservice
    spec:
      containers:
      - name: hostservice-container
        image: ankisile/hostservice:08ddf14c6f5bbfcec16845273c8ed41a8fb444f5
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
